repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.16.3
  hooks:
    - id: ruff-check
      name: lint with ruff
      args: [--fix]
    - id: ruff-check
      name: sort imports with ruff
      args: [--select, I, --fix]
    - id: ruff-format
      name: format with ruff